### ISSUE TITLE
Sorry, that page does not exist, code 34

### ISSUE THREAD

**Issue by williamsdb** [abraham/twitteroauth#1183] opened 2023-07-03 14:33 UTC
**What are you attempting to do**

Posting text with a link & no media - this code worked fine until last Friday - no changes made to code.

**Expected behavior**

Posts a tweet.

**Actual behavior**

Call returns:

```
stdClass Object (
   [errors] => Array (
      [0] => stdClass Object (
         [message] => Sorry, that page does not exist
         [code] => 34
      )
   )
) 
```
**Code example**
```php

$connection = $this->Twitter2_model->twitter_connect($networks[$j]['consumer_key'], $networks[$j]['consumer_secret'], $networks[$j]['oauth_token'], $networks[$j]['oauth_token_secret']);
$reply = $this->Twitter2_model->post_to_twitter($connection, substr($desc,0,256)." ".$item->link);
```

The functions referenced above:

```php

public function twitter_connect($consumer_key, $consumer_secret, $access_token, $access_token_secret, $api="2")
  {

  	// Setup TwitterOAuth
    $connection = new TwitterOAuth($consumer_key, $consumer_secret, $access_token, $access_token_secret);
    $connection->setApiVersion($api);
    return $connection;

  }

public function post_to_twitter($connection, $tweetText, $media='')
	{

		// tweet it
		if (!empty($media)){

      $data = [
        "text" => html_entity_decode($tweetText, ENT_QUOTES),
        "media"=> [
          "media_ids" => [$media],
        ]
      ];
      
      $reply = $connection->post("tweets", $data, true);

    }else{

      $data = ["text" => html_entity_decode($tweetText, ENT_QUOTES)];
      $reply = $connection->post("tweets", $data, true);

   }

   return $reply;
 }
```

**Versions:**

- TwitterOAuth: v4.0.1
- PHP: v8.1.18

**Additional context**

This is the connection:

```
Abraham\TwitterOAuth\TwitterOAuth Object (
[timeout:protected] => 5
[connectionTimeout:protected] => 5
[maxRetries:protected] => 0
[retriesDelay:protected] => 1
[apiVersion:protected] => 2
[decodeJsonAsArray:protected] =>
[userAgent:protected] => TwitterOAuth (
+https://twitteroauth.com
)
[proxy:protected] => Array (
)
[gzipEncoding:protected] => 1
[chunkSize:protected] => 250000
[response:Abraham\TwitterOAuth\TwitterOAuth:private] => Abraham\TwitterOAuth\Response Object (
[apiPath:Abraham\TwitterOAuth\Response:private] =>
[httpCode:Abraham\TwitterOAuth\Response:private] => 0
[headers:Abraham\TwitterOAuth\Response:private] => Array (
)
[body:Abraham\TwitterOAuth\Response:private] => Array (
)
[xHeaders:Abraham\TwitterOAuth\Response:private] => Array (
)
)
[bearer:Abraham\TwitterOAuth\TwitterOAuth:private] =>
[consumer:Abraham\TwitterOAuth\TwitterOAuth:private] => Abraham\TwitterOAuth\Consumer Object (
[key] => <my key>
[secret] => <my secret>
[callbackUrl] =>
)
[token:Abraham\TwitterOAuth\TwitterOAuth:private] => Abraham\TwitterOAuth\Token Object (
[key] => <my key>
[secret] => <my secret>
)
[signatureMethod:Abraham\TwitterOAuth\TwitterOAuth:private] => Abraham\TwitterOAuth\HmacSha1 Object (
)
[attempts:Abraham\TwitterOAuth\TwitterOAuth:private] => 0
) 
```

**Comment by mauriblint** [comment] 2023-07-04 06:33
Facing the same issue with /oauth endpoint, it is working on my local but not in production, weird. Any hints?

**Comment by williamsdb** [comment] 2023-07-04 08:54
Interestingly I see the same - works fine on my local machine but not on my production server.

**Comment by mauriblint** [comment] 2023-07-04 08:59
So far it seems to be a server issue, the difference I'm finding is that on my local server I'm using HTTP2.0 and in production the version of apache doesn't support it, and curl doesn't have HTTP2.0 active, the request is executed with HTTP 1.0, that may be the problem, but now I'm testing (debugging while writing this) on another stage server, with HTTP2.0 enabled and the problem persists, anyway I think the problem comes from there since the POST request made by TwitterOAuth with curl appears to be the same, but Twitter rejects one and accepts another.
Tried also with CURLOPT_SSL_VERIFYHOST in false, and also adding a UserAgent to the headers, but nothing works so far.

**Comment by williamsdb** [comment] 2023-07-04 09:08
Maybe but neither of my servers has been updated since Friday when this was last working. The only thing that has changed, to my knowledge, is Elon has changed the read rate - maybe they implemented something else too that has impacted this?

**Comment by mauriblint** [comment] 2023-07-04 09:12
Yes, I thought the same. But it doesn't make sense, my oauth endpoint fails, it shouldn't be limited in any way. But yes, it coincides with the date on which they made those changes.

I'm 98% sure that it's not related to HTTP1/2, I keep digging

**Comment by mauriblint** [comment] 2023-07-04 10:42
Ok, I was able to fix it by using a proxy. The problem is related to the changes that have been made on Friday. Possibly they have blocked many IPs and many servers must be in a block list. I tried with 6 servers I have, all blocked, just try a curl request from the terminal, and will get the same result.

I am paying for the Twitter API (like many here surely), this is unacceptable. I'll try to contact support somehow. I think we can close this issue here since it is not related to the library.

If anyone else manages to contact Support, please send the information.

**Comment by DougSisk** [comment] 2023-07-04 11:30
Blocked at Linode Dallas. Using a proxy also fixed it for me.

**Comment by williamsdb** [comment] 2023-07-04 11:31
I'm also on Linode, although not at Dallas. Can anyone guide me as to how to route via a proxy please?

**Comment by mauriblint** [comment] 2023-07-04 11:41
I added the proxy on the curl request:

vendor/abraham/twitteroauth/src/TwitterOAuth.php

```
// line 650 aprox
private function request(...) {
...
...
        $options[CURLOPT_PROXY] = $CURLOPT_PROXY;
        $options[CURLOPT_PROXYUSERPWD] = $CURLOPT_PROXYUSERPWD;
}
```

**Comment by DougSisk** [comment] 2023-07-04 11:50
From the tests:
```
$twitter->setProxy([
    'CURLOPT_PROXY' => 'x.x.x.x',
    'CURLOPT_PROXYUSERPWD' => 'user:pass',
    'CURLOPT_PROXYPORT' => 80,
]);
```

May also have to increase timeouts: `$twitter->setTimeouts(60, 60);`

**Comment by williamsdb** [comment] 2023-07-04 11:54
Sorry, but this is going to be a noob question but how do I get a proxy server? You have kindly provided how I change the code but I don't know how to get a proxy. Any help greatly appreciated.

**Comment by mauriblint** [comment] 2023-07-04 11:56
You need to pay for one, I'm using WebShare for years, works pretty well and has many options for proxies. In case you want to pick a proxy, can use my referral link:

https://www.webshare.io/?referral_code=ju8m4j87g6r1

**Comment by williamsdb** [comment] 2023-07-04 12:35
Great, thanks for the pointers and I now too have got it working. Now I need to go back and work out exactly what I have done 🤣

**Closed** 2023-07-05 01:52 UTC
Labels: Bug, Triage
