### ISSUE TITLE
Multiple Error

### ISSUE THREAD

**Issue by GlobalHelp** [abraham/twitteroauth#395] opened 2015-08-22 14:45 UTC
Hello,
I get this error:
>Notice: Use of undefined constant CURLOPT_CAINFO - assumed 'CURLOPT_CAINFO' in >/var/www/html/twitteroauth/src/TwitterOAuth.php on line 297

>Notice: Use of undefined constant CURLOPT_CONNECTTIMEOUT - assumed >'CURLOPT_CONNECTTIMEOUT' in /var/www/html/twitteroauth/src/TwitterOAuth.php on line 298

>Notice: Use of undefined constant CURLOPT_HEADER - assumed 'CURLOPT_HEADER' in >/var/www/html/twitteroauth/src/TwitterOAuth.php on line 299

>Notice: Use of undefined constant CURLOPT_HTTPHEADER - assumed >'CURLOPT_HTTPHEADER' in /var/www/html/twitteroauth/src/TwitterOAuth.php on line 300

>Notice: Use of undefined constant CURLOPT_RETURNTRANSFER - assumed >'CURLOPT_RETURNTRANSFER' in /var/www/html/twitteroauth/src/TwitterOAuth.php on line 301

>Notice: Use of undefined constant CURLOPT_SSL_VERIFYHOST - assumed >'CURLOPT_SSL_VERIFYHOST' in /var/www/html/twitteroauth/src/TwitterOAuth.php on line 302

>Notice: Use of undefined constant CURLOPT_SSL_VERIFYPEER - assumed >'CURLOPT_SSL_VERIFYPEER' in /var/www/html/twitteroauth/src/TwitterOAuth.php on line 303

>Notice: Use of undefined constant CURLOPT_TIMEOUT - assumed 'CURLOPT_TIMEOUT' in >/var/www/html/twitteroauth/src/TwitterOAuth.php on line 304

>Notice: Use of undefined constant CURLOPT_URL - assumed 'CURLOPT_URL' in >/var/www/html/twitteroauth/src/TwitterOAuth.php on line 305

>Notice: Use of undefined constant CURLOPT_USERAGENT - assumed 'CURLOPT_USERAGENT' >in /var/www/html/twitteroauth/src/TwitterOAuth.php on line 306

>Notice: Use of undefined constant CURLOPT_ENCODING - assumed 'CURLOPT_ENCODING' in >/var/www/html/twitteroauth/src/TwitterOAuth.php on line 307

>Fatal error: Call to undefined function Abraham\TwitterOAuth\curl_init() in >/var/www/html/twitteroauth/src/TwitterOAuth.php on line 338

**Comment by abraham** [comment] 2015-08-22 15:28
Duplicate of #312, you need to install curl.

https://secure.php.net/manual/en/curl.installation.php

**Closed by abraham** 2015-08-22 15:28 UTC
