### ISSUE TITLE
Parse error: syntax error, unexpected '[' in /var/sites/src/TwitterOAuth.php on line 266

### ISSUE THREAD

**Issue by mrAddy** [abraham/twitteroauth#402] opened 2015-09-08 14:06 UTC
Just downloaded the master, and tried to set it up, here is the code i am using:

require "autoload.php";

use Abraham\TwitterOAuth\TwitterOAuth;

    if(!isset($_SESSION['oauth_token'])) {

    $connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET);

    $request_token = $connection->oauth('oauth/request_token', array('oauth_callback' => OAUTH_CALLBACK));

    $_SESSION['oauth_token'] = $request_token['oauth_token'];

    $_SESSION['oauth_token_secret'] = $request_token['oauth_token_secret'];

    $url = $connection->url('oauth/authorize', array('oauth_token' => $request_token['oauth_token']));

    } else {

    $request_token = array();
    $request_token['oauth_token'] = $_SESSION['oauth_token'];
    $request_token['oauth_token_secret'] = $_SESSION['oauth_token_secret'];

    if (isset($_REQUEST['oauth_token']) && $request_token['oauth_token'] !== $_REQUEST['oauth_token']) {
        // Abort! Something is wrong.
    }

    $connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $request_token['oauth_token'], $request_token['oauth_token_secret']);

    $access_token = $connection->oauth("oauth/access_token", array("oauth_verifier" => $_REQUEST['oauth_verifier']));

    echo json_encode($access_token);
    }

This is line 266:

    private function uploadMediaChunked($path, $parameters)
        {
        // Init
        $init = $this->http('POST', self::UPLOAD_HOST, $path, [
            'command' => 'INIT',
            'media_type' => $parameters['media_type'],
            'total_bytes' => filesize($parameters['media'])
        ]);

Anyone else getting this error ?

**Comment by abraham** [comment] 2015-09-08 14:41
Duplicate of #393. You are using a version of PHP that is not supported, upgrade to version 5.5 or newer.

**Closed by abraham** 2015-09-08 14:41 UTC

**Comment by mrAddy** [comment] 2015-09-08 14:46
Awesome, that did it, although now i have more errors with regards to the oauth_verifier.  Shall look to see if others have the same.  

Thank you Abraham :)
