### ISSUE TITLE
Failed to Post Tweet, HTTP error code: 404

### ISSUE THREAD

**Issue by Nisar2001** [abraham/twitteroauth#1219] opened 2024-02-08 18:26 UTC
I am trying to do Tweet via my wordpress, I have created a plugin and in plugin folder, I have used composer to import TwitterOAuth library. Now when I run, I get error Failed to Tweet, and HTTP error code: 404.  
![404](https://github.com/abraham/twitteroauth/assets/51190930/12fe4fdf-7c51-4082-8b58-5a556604c3d5)
![plugin](https://github.com/abraham/twitteroauth/assets/51190930/671be3aa-0abd-4f81-9b60-7c2d0ed730da)
![vendor](https://github.com/abraham/twitteroauth/assets/51190930/1f4fb649-ba8c-48af-adef-0a2143e008a9)

here is my code: 

```
<?php

require_once plugin_dir_path(__FILE__) . '/vendor/autoload.php';
use Abraham\TwitterOAuth\TwitterOAuth;

// rest of the code for Button creating and on Click event, tweetViaOAuth1 will be called. 

function tweetViaOAuth1($consumerKey, $consumerSecret, $accessToken, $accessTokenSecret, $tweet) {
    // Authenticate with Twitter using OAuth 1.0a
    $connection = new TwitterOAuth($consumerKey, $consumerSecret, $accessToken, $accessTokenSecret);
    $tweetStatus = $connection->post('statuses/update', ['status' => $tweet]);

    if ($connection->getLastHttpCode() == 200 && !empty($tweetStatus->id_str)) {
        echo "Tweet posted successfully with ID: " . $tweetStatus->id_str . "\n";
    } else {
        echo "Failed to post tweet.\n";
        if (!empty($tweetStatus->errors)) {
            echo "Error message: " . $tweetStatus->errors[0]->message . "\n";
        } else {
            echo "HTTP error code: " . $connection->getLastHttpCode() . "\n";
        }
    }
}
$consumerKey = '7xxxxxxxxxxxxxxxxxxxxxxxxxxx';
$consumerSecret = 'xxxxxxxxxxxxxxxxxxxxxxxxxxx';
$accessToken = '1xxxxxxxxxxxxxxxxxxxxxxxxxxx';
$accessTokenSecret = '7xxxxxxxxxxxxxxxxxxxxxxxxxxxhU';

$tweet = 'Hello Twitter! This is a test tweet via OAuth 1.0a.';

tweetViaOAuth1($consumerKey, $consumerSecret, $accessToken, $accessTokenSecret, $tweet);
```
Please guide me on what is the problem and how can i fix.

**Comment by abraham** [comment] 2024-02-11 18:05
I don't think Twitter let's people use the old v1 API anymore. Try the [v2 API](https://developer.twitter.com/en/docs/twitter-api/tweets/manage-tweets/api-reference/post-tweets).

I think it would look something like:

```php
$connection->setApiVersion('2'); // only needed if not on the latest version of TwitterOAuth
$result = $connection->post("tweets", ["text" => $text], true);
```

**Comment by Nisar2001** [comment] 2024-02-12 01:56
Hello Abraham sir,

I tried the code that you gave idea in the above response.  It did not work. :(

Can you please share a working code entirely that just Prints a variable value to Twitter,, such as this variable content should be post to my twitter: 

$MyTweet = 'This is my first tweet and here is my website, $WebsiteDomain #FollowMe';

**Comment by Nisar2001** [comment] 2024-02-12 02:29
Even have tried totally new code: 
```
function tweetViaOAuth2($bearerToken, $tweet) {

    $data = array(
        'text' => $tweet
    );

    $headers = array(
        'Authorization: Bearer ' . $bearerToken,
        'Content-Type: application/json'
    );

    $postFields = json_encode($data);

    $endpoint = 'https://api.twitter.com/2/tweets';

    $ch = curl_init();

    curl_setopt_array($ch, array(
        CURLOPT_URL => $endpoint,
        CURLOPT_HTTPHEADER => $headers,
        CURLOPT_POST => true,
        CURLOPT_POSTFIELDS => $postFields,
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_HEADER => false
    ));

    $response = curl_exec($ch);
    $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);

    curl_close($ch);

    if ($httpCode == 201) {
        echo "Tweet posted successfully.\n";
    } else {
        echo "Failed to post tweet.\n";
        echo "HTTP error code: " . $httpCode . "\n";
        $errorMsg = 'Error posting tweet: ' . $response;
        auto_tweet_log($errorMsg);
    }
}

$bearerToken = "AxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxGpIjfRMn";
$tweet = 'Hello Twitter! This is a test tweet via OAuth 2.0.';

tweetViaOAuth2($bearerToken, $tweet);
``` 

getting this error back : 
```
Error posting tweet: {
  "title": "Unsupported Authentication",
  "detail": "Authenticating with OAuth 2.0 Application-Only is forbidden for this endpoint.  Supported authentication types are [OAuth 1.0a User Context, OAuth 2.0 User Context].",
  "type": "https://api.twitter.com/2/problems/unsupported-authentication",
  "status": 403
}
```

**Comment by abraham** [comment] 2024-02-12 03:23
I don't have any Twitter apps to validate snippets. https://github.com/abraham/twitteroauth/issues/1192#issuecomment-1673101978 is confirming that the following should work though.

```php
$connection->setApiVersion('2');
$result = $connection->post("tweets", ["text" => $text], true);
```

**Comment by bombarding1** [comment] 2024-02-12 21:36
I can confirm I'm having the same problem. I just installed the library and tested with the following:

```
<?php
require_once 'vendor/autoload.php';
use Abraham\TwitterOAuth\TwitterOAuth;

// OAuth settings
$consumerKey = ''; //removed but confirmed valid
$consumerSecret = ''; //removed but confirmed valid
$accessToken = ''; //removed but confirmed valid
$accessTokenSecret = ''; //removed but confirmed valid

// Create TwitterOAuth object
$twitter = new TwitterOAuth($consumerKey, $consumerSecret, $accessToken, $accessTokenSecret);
$content = $twitter->get("account/verify_credentials");

// I'm able to confirm I am getting a valid connection here and able to see the verified credentials.
print_r($content);

// Create a Tweet
$tweetParams = [
    'text' => 'Check out my twitter ',
];

$status = $twitter->post('tweets', $tweetParams, true);

if ($twitter->getLastHttpCode() == 201) {
    echo "Successfully posted a test tweet.\n";
    echo "Tweet ID: " . $status->data->id . "\n";
    echo "Tweet Text: " . $status->data->text . "\n";
} else {
    echo "Error posting a test tweet.\n";
    echo "HTTP Code: " . $twitter->getLastHttpCode() . "\n";
    echo "API Response:\n";
    var_dump($status);
}
?>
```

As noted above, I'm able to confirm I am getting a valid connection and able to see the verified credentials using
print_r($content);

However when it comes time to post the tweet I get the following:

Error posting a test tweet.
HTTP Code: 404
API Response:
NULL

**Comment by frankboelen** [comment] 2024-02-13 10:55
Just try this:

```
$connection = new TwitterOAuth(env('X_CONSUMER_KEY'), env('X_CONSUMER_SECRET'), env('X_ACCESS_TOKEN'), env('X_ACCESS_TOKEN_SECRET'));
$connection->setApiVersion('2');
$result = $connection->post('tweets', ['text' => "Hi there!"], true);

echo $connection->getLastHttpCode() == 201 ? "Succes!" : "Failed!";

// get result:
print_r($result);
```

**Comment by Nisar2001** [comment] 2024-02-13 17:56
> Just try this:
> 
> ```
> $connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, ACCESS_TOKEN, ACCESS_TOKEN_SECRET);
> $connection->setApiVersion('2');
> $result = $connection->post('tweets', ['text' => "Hi there!"], true);
> 
> echo $connection->getLastHttpCode() == 201 ? "Succes!" : "Failed!";
> 
> // get result:
> print_r($result);
> ```

received this: 
Failed!stdClass Object ( [title] => Forbidden [status] => 403 [detail] => Your client app is not configured with the appropriate oauth1 app permissions for this endpoint. [type] => https://api.twitter.com/2/problems/oauth1-permissions )

**Comment by frankboelen** [comment] 2024-02-14 09:52
I suggest to configure your App with the Twitter Dev platform. Remember to regenerate your keys after changing your configuration.

**Comment by Nisar2001** [comment] 2024-02-16 04:29
> I suggest to configure your App with the Twitter Dev platform. Remember to regenerate your keys after changing your configuration.

I have generated new app after removing old one from my twitter and i am building an wordpress plugin that use my Twitter Auth to send my new posts automatically to my twitter. (I dont want to use any available plugins that do the same, becuase i have something in mind that only can be achieved by custom plugin.)

**Comment by abraham** [comment] 2024-02-18 02:12
I would recommend posting to https://devcommunity.x.com/ regarding correct application configuration. Twitter seems to keep changing those.

**Comment by Eric-Josh** [comment] 2024-02-23 14:20
> > I suggest to configure your App with the Twitter Dev platform. Remember to regenerate your keys after changing your configuration.
> 
> I have generated new app after removing old one from my twitter and i am building an wordpress plugin that use my Twitter Auth to send my new posts automatically to my twitter. (I dont want to use any available plugins that do the same, becuase i have something in mind that only can be achieved by custom plugin.)

@Nisar2001 Ensure your app is on version 2 project in twitter dev console before you use the v2 api

**Comment by Nisar2001** [comment] 2024-02-25 01:38
> > > I suggest to configure your App with the Twitter Dev platform. Remember to regenerate your keys after changing your configuration.
> > 
> > 
> > I have generated new app after removing old one from my twitter and i am building an wordpress plugin that use my Twitter Auth to send my new posts automatically to my twitter. (I dont want to use any available plugins that do the same, becuase i have something in mind that only can be achieved by custom plugin.)
> 
> @Nisar2001 Ensure your app is on version 2 project in twitter dev console before you use the v2 api

![v2](https://github.com/abraham/twitteroauth/assets/51190930/d9366d3a-06cd-49c3-817b-f7c4a3c2958a)

I think, its already version 2 project and v2 API.

**Comment by ZaneCEO** [comment] 2024-03-31 16:49
Hi guys! I can confirm that the package is working properly with this code:

````
$this->twitterOAuth = new TwitterOAuth($oConfig->apiKey, $oConfig->apiSecret, $oConfig->accessToken, $oConfig->accessTokenSecret);
$this->twitterOAuth->setApiVersion('2');
$this->twitterOAuth->post("tweets", ["text" => $message]);
````

You can close the issue, because it's not a bug in the package, but a misconfig of the dev account.

I know because I had the same problem. The issue is due to the "Access Token and Secret" being `Created with Read-only permission` instead of the correct "Read and write"

![image](https://github.com/abraham/twitteroauth/assets/5873880/28981929-fed7-4f13-bbe2-8c60e62be5af)

To fix it, you have to go back to `Settings" and run the `User authentication set up`. 

![image](https://github.com/abraham/twitteroauth/assets/5873880/97371b8a-43f3-4d64-8dc7-5eb9ce2febdd)

From there, you have to set `Read and write`... BUT! Before you can save, you have to fill a couple of others mandatory fields. The `Callback URL` field is mandatory, but not really needed: just input any URL

![image](https://github.com/abraham/twitteroauth/assets/5873880/6e8f10e8-9979-4959-bb7c-943b2d057cc1)

HTH

**Closed** 2024-03-31 18:24 UTC
