### ISSUE TITLE
Make the TwitterOAuth class more configurable and extendable 

### ISSUE THREAD

**Issue by nezarfadle** [abraham/twitteroauth#549] opened 2017-02-23 05:39 UTC
File: [TwitterOAuth.php](https://github.com/abraham/twitteroauth/blob/master/src/TwitterOAuth.php)  

Will it be possible to: 

1. Change the TwitterOAuth class member's accessor to be protected instead of private.
2. Make the configurations injectable instead of being hard coded.

```
const API_VERSION = '1.1';
const API_HOST = 'https://api.twitter.com';
const UPLOAD_HOST = 'https://upload.twitter.com';
const UPLOAD_CHUNK = 40960; // 1024 * 40
```

**Comment by abraham** [comment] 2017-02-23 22:14
Duplicate of #331

**Closed by abraham** 2017-02-23 22:14 UTC
