### ISSUE TITLE
TwitterOAuth::UPLOAD_CHUNK way too small

### ISSUE THREAD

**Issue by clphillips** [abraham/twitteroauth#447] opened 2016-03-07 21:38 UTC
`Abraham\TwitterOAuth\TwitterOAuth::UPLOAD_CHUNK` is set to 40 KB (40960 bytes).

So, to upload a 5 MB video would require 130 separate requests (1 to initialize, 128 to append, 1 to finalize).

5 MB = 5 * 1024 * 1024 = 5242880 bytes
5242880 / 40960 = 128

That's way too much overhead. The chunk size should be configurable (parameter to `upload()`), and should default to something more realistic, like 1 MB.

**Comment by abraham** [comment] 2016-03-07 22:53
Duplicate of #436

**Closed by abraham** 2016-03-07 22:53 UTC
