### ISSUE TITLE
New APIs for messages

### ISSUE THREAD

**Issue by originalnickname** [abraham/twitteroauth#703] opened 2018-08-12 14:34 UTC
Hi,
as you may know, Twitter will change APIs for managing messages.
At the moment I'm trying the one to send a direct message:
https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/api-reference/new-event
Using the code below I get null as result.
Is my code wrong or the library doesn't support these new APIs?
Thanks

I am using this twitteroauth.php:
https://github.com/abraham/twitteroauth/blob/master/src/TwitterOAuth.php

```
<?php
$connection = new TwitterOAuth( ... );

$parameters = array(
    'event' => array(
        'type' => "message_create",
        'message_create' => array(
            'target' => array(
                'recipient_id' => 1452733158
            ),
            'message_data' => array(
                'text' => "Hello world"
            )
        )
    )
);

$result = $connection->post("direct_messages/events/new", array(json_encode($parameters)));

echo json_encode($result,JSON_PRETTY_PRINT);
?>
```

**Comment by sololance** [comment] 2018-08-15 08:00
Hi!

You need to add pass true as last parameter. Please check the documentation.

Thanks.

**Comment by abraham** [comment] 2018-08-15 12:12
Duplicate of #699

**Closed by abraham** 2018-08-15 12:12 UTC
