### ISSUE TITLE
Warning in json_decode()

### ISSUE THREAD

**Issue by royopa** [abraham/twitteroauth#289] opened 2015-01-08 09:54 UTC
( ! ) Warning: json_decode(): option JSON_BIGINT_AS_STRING not implemented in /media/rodrigo/01CF1AB05F7F53A0/projects/api-rosetta-code/samples/get-users-show/php-twitter/vendor/abraham/twitteroauth/src/TwitterOAuth.php on line 275
Call Stack
#	Time	Memory	Function	Location
1	0.0008	228776	{main}( )	../index.php:0
2	0.0109	306088	Abraham\TwitterOAuth\TwitterOAuth->get( )	../index.php:53
3	0.0109	306248	Abraham\TwitterOAuth\TwitterOAuth->http( )	../TwitterOAuth.php:164
4	0.8354	322136	Abraham\TwitterOAuth\TwitterOAuth->jsonDecode( )	../TwitterOAuth.php:192
5	0.8355	322280	json_decode ( )	../TwitterOAuth.php:275

**Comment by abraham** [comment] 2015-01-08 17:26
Duplicate of #288

**Closed by abraham** 2015-01-08 17:26 UTC
