### ISSUE TITLE
GZIP encoding issue on Google App Engine

### ISSUE THREAD

**Issue by javiermarinros** [abraham/twitteroauth#418] opened 2015-10-23 12:44 UTC
I've experienced some trouble with Google App Engine cURL implementation not decoding gzip responses properly. It would be nice an option to disable compression in order to avoid this issue, something like:

`$connection->gzip = false;`

**Comment by abraham** [comment] 2015-10-26 16:55
Duplicate of #408.

**Closed by abraham** 2015-10-26 16:55 UTC
