### ISSUE TITLE
Async FINALIZE media/upload

### ISSUE THREAD

**Issue by PrivalovAlex** [abraham/twitteroauth#482] opened 2016-07-17 22:30 UTC
As I read here https://dev.twitter.com/rest/media/uploading-media
twitter has ability to upload large video files

> Duration should be between 0.5 seconds and 30 seconds (sync) / 140 seconds (async)
> File size should not exceed 15 mb (sync) / 512 mb (async)

And here I read https://dev.twitter.com/rest/reference/post/media/upload-finalize

> The async finalize approach is used for cases where media processing requires more time. In future, all video and animated GIF processing will only be supported using async finalize.

So, what about support async finalize in you library?

**Comment by abraham** [comment] 2016-07-17 23:42
That would probably be good to support.

**Comment by PrivalovAlex** [comment] 2016-07-18 00:00
For myself I made it in this way:
class TwitterOAuth extends Config
{
.......................................
.....................................
public function getUploadStatus($media_id)
	{
		return $this->http('GET', self::UPLOAD_HOST, 'media/upload', array(
					'command' => 'STATUS',
					'media_id' => $media_id,
		));
	}

private function uploadMediaChunked($path, array $parameters)
	{
// Init
		$arr = [
			'command' => 'INIT',
			'media_type' => $parameters['media_type'],
			'total_bytes' => filesize($parameters['media'])
		];
		if (!empty($parameters['media_category'])) {
			$arr['media_category'] = $parameters['media_category']; //need for activate async
		}
		$init = $this->http('POST', self::UPLOAD_HOST, $path, $arr);
.................................................................................................................
}

and use class in this way:
$params = array(
						'status' => 'test tweet text',
					);
$vres = $connection->upload('media/upload', array(
								'media' => $video_file_full_path,
								'media_type' => 'video/mp4',
								'media_category' => 'tweet_video',   //need for activate async
									), true);
							if (!empty($vres->media_id_string)) {
								$media_id = $vres->media_id_string;
								while ($vres->processing_info->state == 'pending' || $vres->processing_info->state == 'in_progress') {
									sleep($vres->processing_info->check_after_secs);
									$vres = $connection->getUploadStatus($media_id);
								}
								if ($vres->processing_info->state == 'succeeded') {
                                                                        // Video is ready
									$params['media_ids'] = $vres->media_id_string;
								}
							}
$connection->post('statuses/update', $params);

**Comment by PrivalovAlex** [comment] 2016-07-18 00:03
It is not realy good practice, because I made sync emulation of async api
>>while (...
>>sleep(...

**Comment by codex-corp** [comment] 2016-08-11 11:32
@PrivalovAlex 
It works for me , thanks !

**Comment by abraham** [comment] 2017-02-23 22:33
Duplicate of #490

**Closed by abraham** 2017-02-23 22:33 UTC
Labels: Explore, Media
